services:
  - type: web
    name: weather-mcp-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false
